//../rtl/nice_coprocessor/csr_unit.v
//../rtl/nice_coprocessor/decode_dispatch.v
//../rtl/nice_coprocessor/dummy_mma_top.v
//../rtl/nice_coprocessor/e203_subsys_nice_core.sv
//../rtl/nice_coprocessor/icb_unalign_bridge.sv
//../rtl/nice_coprocessor/inst_pingpong_buf.v
//../rtl/nice_coprocessor/inst_tracker.v
//../rtl/nice_coprocessor/MMA/accumulator_array.sv
//../rtl/nice_coprocessor/MMA/bias_loader.sv
//../rtl/nice_coprocessor/MMA/compute_core.sv
//../rtl/nice_coprocessor/MMA/data_setup.sv
//../rtl/nice_coprocessor/MMA/ia_buffer_wrapper.sv
//../rtl/nice_coprocessor/MMA/ia_loader.sv
//../rtl/nice_coprocessor/MMA/icb_arbiter.sv
//../rtl/nice_coprocessor/MMA/icb_ext_flat_adapter.sv
//../rtl/nice_coprocessor/MMA/icb_mux_5to1.sv
//../rtl/nice_coprocessor/MMA/kernel_loader.sv
//../rtl/nice_coprocessor/MMA/mma_controller.sv
//../rtl/nice_coprocessor/MMA/mma_top.sv
//../rtl/nice_coprocessor/MMA/oa_writer.sv
//../rtl/nice_coprocessor/MMA/shift_accumulator.sv
//../rtl/nice_coprocessor/MMA/vec_requant.sv
//../rtl/nice_coprocessor/MMA/vec_s8_to_fifo.sv
//../rtl/nice_coprocessor/MMA/ws_systolic_array.sv
//../rtl/nice_coprocessor/MMA/ws_systolic_cell.sv
//../rtl/nice_coprocessor/wbu.v
//../rtl/nice_coprocessor/wb_pingpong_buf.v
//../rtl/top_ai_engine.sv

../rtl/GV/top_ai_engine.v
../rtl/GV/scc40nll_vhsc40_hvt.v
../rtl/GV/scc40nll_vhsc40_lvt.v
../rtl/GV/scc40nll_vhsc40_rvt.v
