../../rtl/nice_coprocessor/csr_unit.v
../../rtl/nice_coprocessor/decode_dispatch.v
../../rtl/nice_coprocessor/dummy_mma_top.v
../../rtl/nice_coprocessor/icb_unalign_bridge.sv
../../rtl/nice_coprocessor/icb2axi/axi_buffer.v
../../rtl/nice_coprocessor/icb2axi/fifo_async.v
../../rtl/nice_coprocessor/icb2axi/icb2axi.v
../../rtl/nice_coprocessor/inst_pingpong_buf.v
../../rtl/nice_coprocessor/inst_tracker.v
../../rtl/nice_coprocessor/axi_top/mma_axil_top.sv
../../rtl/nice_coprocessor/axi_top/axil_top_with_ram.sv
../../rtl/nice_coprocessor/axil_reg_if.v
../../rtl/nice_coprocessor/axil_reg_if_wr.v
../../rtl/nice_coprocessor/axil_reg_if_rd.v
../../rtl/nice_coprocessor/MMA/accumulator_array.sv
../../rtl/nice_coprocessor/MMA/bias_loader.sv
../../rtl/nice_coprocessor/MMA/bias_loader_buffer.sv
../../rtl/nice_coprocessor/MMA/bias_loader_ctrl.sv
../../rtl/nice_coprocessor/MMA/bias_mux.sv
../../rtl/nice_coprocessor/MMA/block_dma.sv
../../rtl/nice_coprocessor/MMA/block_dma_arbiter.sv
../../rtl/nice_coprocessor/MMA/compute_core.sv
../../rtl/nice_coprocessor/MMA/data_setup.sv
../../rtl/nice_coprocessor/MMA/de_diagonalizer.sv
../../rtl/nice_coprocessor/MMA/ia_buffer_wrapper.sv
../../rtl/nice_coprocessor/MMA/ia_loader.sv
../../rtl/nice_coprocessor/MMA/ia_loader_cache_mgr.sv
../../rtl/nice_coprocessor/MMA/ia_loader_ctrl.sv
../../rtl/nice_coprocessor/MMA/icb_arbiter.sv
../../rtl/nice_coprocessor/MMA/icb_ext_flat_adapter.sv
../../rtl/nice_coprocessor/MMA/icb_mux_5to1.sv
../../rtl/nice_coprocessor/MMA/icb_read_dma_adapter.sv
../../rtl/nice_coprocessor/MMA/icb_write_dma_adapter.sv
../../rtl/nice_coprocessor/MMA/kernel_block_dma.sv
../../rtl/nice_coprocessor/MMA/kernel_loader.sv
../../rtl/nice_coprocessor/MMA/kernel_loader_buffer.sv
../../rtl/nice_coprocessor/MMA/kernel_loader_ctrl.sv
../../rtl/nice_coprocessor/MMA/mma_controller.sv
../../rtl/nice_coprocessor/MMA/mma_top.sv
../../rtl/nice_coprocessor/MMA/oa_writer.sv
../../rtl/nice_coprocessor/MMA/ps_buffer.sv
../../rtl/nice_coprocessor/MMA/ps_buffer_fifo.sv
../../rtl/nice_coprocessor/MMA/pseudo_dual_port_ram.v
../../rtl/nice_coprocessor/MMA/shift_accumulator.sv
../../rtl/nice_coprocessor/MMA/vec_requant.sv
../../rtl/nice_coprocessor/MMA/vec_s8_to_fifo.sv
../../rtl/nice_coprocessor/MMA/ws_systolic_array.sv
../../rtl/nice_coprocessor/MMA/ws_systolic_cell.sv
../../rtl/nice_coprocessor/wbu.v
../../rtl/nice_coprocessor/wb_pingpong_buf.v
