+incdir+../include
+incdir+../../e203_soc_ip/include
../rtl/nice_coprocessor/MMA/accumulator_array.sv
../rtl/nice_coprocessor/MMA/bias_loader.sv
../rtl/nice_coprocessor/MMA/bias_loader_buffer.sv
../rtl/nice_coprocessor/MMA/bias_loader_ctrl.sv
../rtl/nice_coprocessor/MMA/bias_mux.sv
../rtl/nice_coprocessor/MMA/axi_block_dma_arbiter.sv
../rtl/nice_coprocessor/MMA/axi_dual_block_dma.sv
../rtl/nice_coprocessor/MMA/block_dma.sv
../rtl/nice_coprocessor/MMA/block_dma_arbiter.sv
../rtl/nice_coprocessor/MMA/compute_core.sv
../rtl/nice_coprocessor/MMA/data_setup.sv
../rtl/nice_coprocessor/MMA/de_diagonalizer.sv
../rtl/nice_coprocessor/MMA/ia_buffer_wrapper.sv
../rtl/nice_coprocessor/MMA/ia_loader.sv
../rtl/nice_coprocessor/MMA/ia_loader_cache_mgr.sv
../rtl/nice_coprocessor/MMA/ia_loader_ctrl.sv
../rtl/nice_coprocessor/MMA/icb_arbiter.sv
../rtl/nice_coprocessor/MMA/icb_ext_flat_adapter.sv
../rtl/nice_coprocessor/MMA/icb_mux_5to1.sv
../rtl/nice_coprocessor/MMA/icb_read_dma_adapter.sv
../rtl/nice_coprocessor/MMA/icb_write_dma_adapter.sv
../rtl/nice_coprocessor/MMA/kernel_block_dma.sv
../rtl/nice_coprocessor/MMA/kernel_loader.sv
../rtl/nice_coprocessor/MMA/kernel_loader_buffer.sv
../rtl/nice_coprocessor/MMA/kernel_loader_ctrl.sv
../rtl/nice_coprocessor/MMA/mma_controller.sv
../rtl/nice_coprocessor/MMA/mma_top.sv
../rtl/nice_coprocessor/MMA/oa_writer.sv
../rtl/nice_coprocessor/MMA/ps_buffer.sv
../rtl/nice_coprocessor/MMA/ps_buffer_fifo.sv
../rtl/nice_coprocessor/MMA/pseudo_dual_port_ram.v
../rtl/nice_coprocessor/MMA/vec_requant.sv
../rtl/nice_coprocessor/MMA/vec_s8_to_fifo.sv
../rtl/nice_coprocessor/MMA/ws_systolic_array.sv
../rtl/nice_coprocessor/MMA/shift_accumulator.sv
../rtl/nice_coprocessor/MMA/ws_systolic_cell.sv
