+incdir+../include
+incdir+../../e203_soc_ip/include
+incdir+../rtl/video_sys/ov5640

../rtl/video_sys/sram/sram_icb.v
../rtl/video_sys/sram/sram_icb_ctrl.v
../rtl/video_sys/sram/sirv_1cyc_sram_ctrl.v
../rtl/video_sys/sram/sram.v
../rtl/video_sys/sram/sram_4096x8_macro_wrap.v
../rtl/video_sys/video_sys_top.sv
../rtl/video_sys/ov5640/ov5640_icb_top.v
../rtl/video_sys/ov5640/icb2dcmi.v
../rtl/video_sys/ov5640/ov5640_y8_top.v
../rtl/video_sys/general/sirv_gnrl_bufs.v
../rtl/video_sys/general/sirv_gnrl_dffs.v
../rtl/video_sys/general/sirv_gnrl_xchecker.v
../rtl/video_sys/general/sirv_gnrl_ram.v
../rtl/video_sys/general/sirv_sim_ram.v
../rtl/video_sys/general/e203_clkgate.v
